### ISSUE TITLE
v1.0.0 Release planning

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-wallet#113]
The `v1.0.0` version of the library will be released soon, this mainly builds upon the `TypeScript` rewrite done by @the-jackalope in https://github.com/ethereumjs/ethereumjs-wallet/pull/93.

Testing of the current `master` branch of the library is encouraged, please also note if you have suggestions for the release.

TODOs:
- [x] Integrate to-be-released `ethereumjs-util` `v7.0.0` version mainly based on the work done here https://github.com/ethereumjs/ethereumjs-util/pull/228 from @cgewecke 
- [x] Wait for new `hdkey` dependency release (see [comment](https://github.com/ethereumjs/ethereumjs-wallet/issues/113#issuecomment-622593411) below) to have a `secp256k1` dependencies on `v4`, release is [promised](https://github.com/cryptocoinjs/hdkey/pull/32#issuecomment-634699109) over on the library 😄
- [x] Remove `ProviderEngine` (needs discussion) https://github.com/ethereumjs/ethereumjs-wallet/issues/115
- [x] Update to patched `ethereumjs-util` `v7.0.2` release (BN.js v5/v4 interoperability issue)
- [x] Optional: add CHANGELOG entry from v0.6.4 release (on its own `v0.6.x` branch)
- [x] Optional: give `dependencies ` and `devDependencies`  another look, some more explicit `TypeScript` version update (currently `^3.2.2`)

**Comment by kumavis** [comment]
@holgerd77 im interested in a `0.6.x` patch with node v12 support
trying to identify a last-good commit for the `0.6.x` version range
https://github.com/ethereumjs/ethereumjs-wallet/commits/master
can you help me identify the first breaking change commit?
changelog did not mention anything
https://github.com/ethereumjs/ethereumjs-wallet/blob/master/CHANGELOG.md

**Comment by kumavis** [comment]
@holgerd77 can you add [ethereumjs committers team](https://github.com/orgs/ethereumjs/teams/committers) (or just me) to this repo? I'd like to be able to create and manage branches

**Comment by holgerd77** [comment]
@kumavis have added you, please just don't do but communicate on what you are doing and planning frequently, thanks 🙂

**Comment by kumavis** [comment]
here is my `0.6.x` proposal https://github.com/ethereumjs/ethereumjs-wallet/pull/114

**Comment by holgerd77** [comment]
`hdkey` dependency has an open PR https://github.com/cryptocoinjs/hdkey/pull/32 for an `secp2561` update to v4, might be worth the wait for a release to integrate a new version (have asked on GitHub).

**Comment by kumavis** [comment]
v4 landed :+1:
